version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: school-bell-postgres
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME_PRODUCTION}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD_PRODUCTION}
      POSTGRES_DB: ${DATABASE_NAME_PRODUCTION}
    env_file:
      - .env
    ports:
      - "30456:5432"
    volumes:
      - postgres-school-bell-data:/var/lib/postgresql/data
    networks:
      - ${NETWORK_NAME}

networks:
  school-bell-network:
    name: ${NETWORK_NAME}
    driver: bridge

volumes:
  postgres-school-bell-data:
    driver: local
